### ISSUE TITLE
"pymongo.errors.CursorNotFound: cursor id '12487821143' not valid at server"   error is thrown after generating few images

### ISSUE THREAD

**Issue by AnBera** [AnBera/previewImageGeneration#5]
Please read the error log from end. 
This [link](https://stackoverflow.com/questions/24199729/pymongo-errors-cursornotfound-cursor-id-not-valid-at-server)  might give some insights.

    =====error log=====
```
[0805/062641.959:INFO:CONSOLE(26)] "Mixed Content: The page at 'https://www.blogger.com/navbar.g?targetBlogID=28148811&blogName=Jonathan%27s+IT+Blog+-+Sharing+Pointers&publishMode=PUBLISH_MODE_HOSTED&navbarType=BLUE&layoutType=LAYOUTS&searchRoot=http://blog.jonathanroussel.com/search&blogLocale=en&v=2&homepageUrl=http://blog.jonathanroussel.com/&targetPostID=3200088498617957280&blogPostOrPageUrl=http://blog.jonathanroussel.com/2011/01/custom-site-logo-not-appearing-on.html&vt=-8163734532821564925&usegapi=1&jsh=m%3B%2F_%2Fscs%2Fapps-static%2F_%2Fjs%2Fk%3Doz.gapi.en_US.tkLGB8oygGw.O%2Fam%3DwQE%2Fd%3D1%2Frs%3DAGLTcCOVrdiUrdoKYhlUTq9WIvZT-VXTAA%2Fm%3D__features__#id=navbar-iframe&_gfid=navbar-iframe&parent=http%3A%2F%2Fblog.jonathanroussel.com&pfname=&rpctoken=34236395' was loaded over a secure connection, but contains a form that targets an insecure endpoint 'http://blog.jonathanroussel.com/search'. This endpoint should be made available over a secure connection.", source: https://www.blogger.com/navbar.g?targetBlogID=28148811&blogName=Jonathan%27s+IT+Blog+-+Sharing+Pointers&publishMode=PUBLISH_MODE_HOSTED&navbarType=BLUE&layoutType=LAYOUTS&searchRoot=http://blog.jonathanroussel.com/search&blogLocale=en&v=2&homepageUrl=http://blog.jonathanroussel.com/&targetPostID=3200088498617957280&blogPostOrPageUrl=http://blog.jonathanroussel.com/2011/01/custom-site-logo-not-appearing-on.html&vt=-8163734532821564925&usegapi=1&jsh=m%3B%2F_%2Fscs%2Fapps-static%2F_%2Fjs%2Fk%3Doz.gapi.en_US.tkLGB8oygGw.O%2Fam%3DwQE%2Fd%3D1%2Frs%3DAGLTcCOVrdiUrdoKYhlUTq9WIvZT-VXTAA%2Fm%3D__features__#id=navbar-iframe&_gfid=navbar-iframe&parent=http%3A%2F%2Fblog.jonathanroussel.com&pfname=&rpctoken=34236395 (26)
[0805/062648.389:INFO:CONSOLE(2)] "JQMIGRATE: Migrate is installed, version 1.4.1", source: https://efy.in/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.4.1 (2)
[0805/062654.104:INFO:CONSOLE(0)] "The resource https://k4z6w9b5.stackpathcdn.com/v2/9b4a1283/shrMain.min.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.", source:  (0)
[0805/062658.414:INFO:CONSOLE(1)] "ellipsify", source: https://widgets.services.microsoft.com/v1/widgets.js?brand=Msdn&lang=en-US&ver=4.9.0.0 (1)
[0805/062659.846:INFO:CONSOLE(572)] "Powered by AMP ΓÜí HTML ΓÇô Version 1907231757120", source: https://cdn.ampproject.org/rtv/011907231757120/amp4ads-v0.js (572)
[0805/062715.829:INFO:CONSOLE(1)] "Uncaught SyntaxError: Unexpected token <", source: http://www.ashokraja.me/themes/styles/gist.js (1)
[0805/062715.979:INFO:CONSOLE(6)] "Uncaught TypeError: Cannot read property 'indexOf' of undefined", source: http://www.ashokraja.me/Scripts/gist.js (6)
[0805/062716.090:INFO:CONSOLE(68)] "Uncaught ReferenceError: WebForm_InitCallback is not defined", source: http://www.ashokraja.me/articles/How-to-Show-and-Hide-a-Modal-Pop-up-Dialog-in-a-SharePoint-2013-Page-or-a-Visual-WebPart (68)
[0805/062716.332:INFO:CONSOLE(1)] "Uncaught SyntaxError: Unexpected token <", source: http://www.ashokraja.me/themes/styles/highlight.js (1)
[0805/062716.335:INFO:CONSOLE(58)] "Uncaught ReferenceError: hljs is not defined", source: http://www.ashokraja.me/articles/How-to-Show-and-Hide-a-Modal-Pop-up-Dialog-in-a-SharePoint-2013-Page-or-a-Visual-WebPart (58)
[0805/062716.336:INFO:CONSOLE(1)] "Uncaught SyntaxError: Unexpected token <", source: http://www.ashokraja.me/themes/styles/gist.js (1)
[0805/062716.338:INFO:CONSOLE(6)] "Uncaught TypeError: Cannot read property 'indexOf' of undefined", source: http://www.ashokraja.me/Scripts/gist.js (6)
[0805/062716.357:INFO:CONSOLE(1)] "Uncaught SyntaxError: Unexpected token <", source: http://www.ashokraja.me/themes/styles/highlight.js (1)
[0805/062716.358:INFO:CONSOLE(135)] "Uncaught ReferenceError: hljs is not defined", source: http://www.ashokraja.me/articles/How-to-Show-and-Hide-a-Modal-Pop-up-Dialog-in-a-SharePoint-2013-Page-or-a-Visual-WebPart (135)
[0805/062716.359:INFO:CONSOLE(1)] "Uncaught SyntaxError: Unexpected token <", source: http://www.ashokraja.me/themes/styles/gist.js (1)
[0805/062716.361:INFO:CONSOLE(6)] "Uncaught TypeError: Cannot read property 'indexOf' of undefined", source: http://www.ashokraja.me/Scripts/gist.js (6)
[0805/062716.363:INFO:CONSOLE(1)] "Uncaught SyntaxError: Unexpected token <", source: http://www.ashokraja.me/themes/styles/highlight.js (1)
[0805/062716.364:INFO:CONSOLE(195)] "Uncaught ReferenceError: hljs is not defined", source: http://www.ashokraja.me/articles/How-to-Show-and-Hide-a-Modal-Pop-up-Dialog-in-a-SharePoint-2013-Page-or-a-Visual-WebPart (195)
[0805/062716.726:INFO:CONSOLE(1)] "Uncaught ReferenceError: SyntaxHighlighter is not defined", source:  (1)
[0805/062716.754:INFO:CONSOLE(10)] "Uncaught ReferenceError: SyntaxHighlighter is not defined", source: http://www.ashokraja.me/Scripts/syntaxhighlighter/shInit.js (10)
x_order_2: colinear!
[0805/062729.699:INFO:CONSOLE(572)] "Powered by AMP ΓÜí HTML ΓÇô Version 1907231757120", source: https://cdn.ampproject.org/rtv/011907231757120/amp4ads-v0.js (572)
[0805/062731.327:INFO:CONSOLE(8)] "JQMIGRATE: Migrate is installed, version 1.4.1", source: https://s0.wp.com/_static/??-eJyFkOsKwjAMhV/Iroh0+Ed8lq3LSmpvNq1Dn95OJ8xtKASSkI+Tk/AhMHTS5A6I6xLXDPE+pUrTjv8CmEUVmwSVRfeBpXcJXBrZ4ClZIGoUbEytb9EAywSxAC6VNb1fcjazYLJCRzyCKas6Nqouug3170PQ3RCGv5iGFBp5YREIHyvPMy+UW5IRQ0Jfut4b41fqM3zATkF6/e9dsjbbwCZPZ3vaC3E8iLoWB/0ECeGXGw== (8)
[0805/062740.135:INFO:CONSOLE(0)] "The resource https://k4z6w9b5.stackpathcdn.com/v2/9b4a1283/shrMain.min.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.", source:  (0)
[0805/062746.947:INFO:CONSOLE(0)] "The resource https://pagead2.googlesyndication.com/pagead/js/r20190729/r20190131/show_ads_impl.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.", source:  (0)
[0805/062752.048:INFO:CONSOLE(572)] "Powered by AMP ΓÜí HTML ΓÇô Version 1907231757120", source: https://cdn.ampproject.org/rtv/011907231757120/amp4ads-v0.js (572)
[0805/062755.130:INFO:CONSOLE(1)] "Uncaught TagError: adsbygoogle.push() error: No slot size for availableWidth=111", source: http://pagead2.googlesyndication.com/pagead/show_ads.js (1)
[0805/062755.199:INFO:CONSOLE(1595)] "A parser-blocking, cross site (i.e. different eTLD+1) script, http://www.google-analytics.com/ga.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.", source: http://howtosharepointvideos.blogspot.com/2009/12/sharepoint-2010-video-tutorials-channel.html (1595)
[0805/062755.200:INFO:CONSOLE(1595)] "A parser-blocking, cross site (i.e. different eTLD+1) script, http://www.google-analytics.com/ga.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.", source: http://howtosharepointvideos.blogspot.com/2009/12/sharepoint-2010-video-tutorials-channel.html (1595)
[0805/062802.842:INFO:CONSOLE(2)] "JQMIGRATE: Migrate is installed, version 1.4.1", source: https://blogs.msdn.microsoft.com/jibranj/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.4.1 (2)
[0805/062806.204:INFO:CONSOLE(572)] "Powered by AMP ΓÜí HTML ΓÇô Version 1907231757120", source: https://cdn.ampproject.org/rtv/011907231757120/amp4ads-v0.js (572)
[0805/062808.231:INFO:CONSOLE(2)] "JQMIGRATE: Migrate is installed, version 1.4.1", source: https://www.itidea.nl/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.4.1 (2)
[0805/062811.013:INFO:CONSOLE(572)] "Powered by AMP ΓÜí HTML ΓÇô Version 1907231757120", source: https://cdn.ampproject.org/rtv/011907231757120/amp4ads-v0.js (572)
[0805/062814.690:INFO:CONSOLE(0)] "The resource https://pagead2.googlesyndication.com/pagead/js/r20190729/r20190131/show_ads_impl.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.", source:  (0)
[0805/062816.468:INFO:CONSOLE(2)] "JQMIGRATE: Migrate is installed, version 1.4.1", source: https://blogs.msdn.microsoft.com/how24/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.4.1 (2)
[0805/062827.109:INFO:CONSOLE(2)] "JQMIGRATE: Migrate is installed, version 1.4.1", source: https://blogs.msdn.microsoft.com/timquin/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.4.1 (2)
[0805/062839.445:INFO:CONSOLE(0)] "The resource https://k4z6w9b5.stackpathcdn.com/v2/9b4a1283/shrMain.min.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.", source:  (0)
[0805/062846.682:INFO:CONSOLE(8)] "JQMIGRATE: Migrate is installed, version 1.4.1", source: https://s2.wp.com/_static/??-eJyNkH0KwjAMxS9kV0Q2/Ee8gXeoM87Upq1NuqGnt4oisvkBgQTye++F6CEq9K3LO2BtS50ypPOjVZZn+hugCLtkBCpC/4Tb4AW83NgYWAiYTQcTWwpbdKAyQyqAlxKzDxPc+0noe4ThJ2ZBommPKgHjZZQuByh36ZiAMJMOUfBlUYErWy/GVW2gGHyZ+U+HElcEjD1sTI+dEQyjx3yQkrn/cE2reV0vF3XT1At7BRE/nE8= (8)
[0805/062852.373:INFO:CONSOLE(52)] "ErrorUtils caught an error: "Tried to listen to element of type click from Error: Cannot listen to an unde...". Subsequent errors won't be logged; see https://fburl.com/debugjs.", source: https://www.facebook.com/rsrc.php/v3/yK/r/NtkWbvq6Qjp.js?_nc_x=Ij3Wp8lg5Kz (52)
[0805/062854.141:INFO:CONSOLE(0)] "Mixed Content: The page at 'https://chsakell.com/2015/08/23/building-single-page-applications-using-web-api-and-angularjs-free-e-book/' was loaded over HTTPS, but requested an insecure image 'http://sync.teads.tv/um?eid=49&uid=23c4ce8f-5fab-41bd-9ab8-bffb019cfbe9&fb='. This content should also be served over HTTPS.", source: https://sync.teads.tv/iframe (0)
D:\previewImageGeneration\takescreenshot.py:26: DeprecationWarning: save is deprecated. Use insert_one or replace_one instead
  collection.save(x)
[0805/063347.739:INFO:CONSOLE(52)] "ErrorUtils caught an error: "Tried to listen to element of type click from Error: Cannot listen to an unde...". Subsequent errors won't be logged; see https://fburl.com/debugjs.", source: https://www.facebook.com/rsrc.php/v3/yK/r/NtkWbvq6Qjp.js?_nc_x=Ij3Wp8lg5Kz (52)
Traceback (most recent call last):
  File "D:\previewImageGeneration\takescreenshot.py", line 14, in <module>
    for x in collection.find({ "is_image_generated": {"$exists": False} }):#.limit(10):
  File "C:\Users\bookmarkbuddy\AppData\Local\Programs\Python\Python37\lib\site-packages\pymongo\cursor.py", line 976, in __next__
    if len(self.__data) or self._refresh():
  File "C:\Users\bookmarkbuddy\AppData\Local\Programs\Python\Python37\lib\site-packages\pymongo\cursor.py", line 925, in _refresh
    self.__id))
  File "C:\Users\bookmarkbuddy\AppData\Local\Programs\Python\Python37\lib\site-packages\pymongo\cursor.py", line 839, in __send_message
    codec_options=self.__codec_options)
  File "C:\Users\bookmarkbuddy\AppData\Local\Programs\Python\Python37\lib\site-packages\pymongo\helpers.py", line 110, in _unpack_response
    cursor_id)
pymongo.errors.CursorNotFound: cursor id '12487821143' not valid at server
```

**Comment by ayanb07** [comment]
This https://stackoverflow.com/questions/24199729/pymongo-errors-cursornotfound-cursor-id-not-valid-at-server link gives batch_size solution similar to my limit solution. Let's do the batch size change.

**Comment by ayanb07** [comment]
Done.

**Comment by AnBera** [comment]
Same issue happens again. Screenprint attached. 

![Screenshot 2019-08-06 at 5 44 35 PM](https://user-images.githubusercontent.com/2425195/62539060-f1429a80-b871-11e9-88e0-f39ea3a14706.png)
